###########################################
#         高可用Eureka Server 配置         #
#           Linux数据库，Redis             #
#             Linux Nginx代理              #
############################################
eureka:
  client:
    serviceUrl:
      defaultZone: http://peer1:8801/eureka/
  instance:
    status-page-url: http://localhost:${server.port}/swagger-ui.html

spring:
  datasource:
    name: pro
    url: jdbc:mysql://127.0.0.1:3306/kings_erp?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT
    username: root
    password: qwe123
    hikari:
      maximumPoolSize: 10
      minimumIdle: 2
      idleTimeout: 600000
      connectionTimeout: 30000
      maxLifetime: 1800000
  redis:
    database: 0
    host: 127.0.0.1
    password: qwe123
    port: 6379
    timeout: 7000
    lettuce:
      pool:
        max-idle: 500
        min-idle: 50
        max-active: 2000
        max-wait: 1000